### ISSUE TITLE
Missing all albums in 1.2.0.1

### ISSUE THREAD

**Issue by a-dekker** [djselbeck/smpc#1]
The latest version won't show any albums (artists are shown). Rebuilding the database does not help (it won't find any album to index, only artists). Reverting to 1.1.8-1 brings back the albums. Starting from the commandline does not give clues of what's going on (no new error messages as far as I can tell).

Could this be a specific local database issue?

P.s. compliments regarding this great app.

**Comment by djselbeck** [comment]
Which MPD version are you using? Changed a bit one the network side. Perhaps I have to do some version checking.

**Comment by a-dekker** [comment]
mpd --version
mpd (MPD: Music Player Daemon) 0.16.7

**Comment by djselbeck** [comment]
I've uploadad a new version 1.2.1. Can you try this version?

**Comment by a-dekker** [comment]
Yes, the albums do show up now, great!
Was it related to the mpd server version as you suspected?

**Comment by djselbeck** [comment]
Yes, your MPD version is quite old. Artist albums are perhaps still broken?

I have to implement some checks to enable some features only for new versions. I'll do it later when I have time

**Comment by a-dekker** [comment]
Well, all looks fine at first glance.
I am using debian 7.9 (recently released, although there is debian 8 now of course) which comes with this version. I tried upgrading mpd, but that did not work out well.
Again, thanks for the swift response.

**Comment by djselbeck** [comment]
No problem. I will clean it up later. Thanks for your report. This was very helpful and opened my eyes not to only look at the current protocol documentation.
