### ISSUE TITLE
Not working in SFOS 2.1.0.9

### ISSUE THREAD

**Issue by a-dekker** [djselbeck/smpc#8]
SMPC segfaults sooner or later running in the latest Sailfish release.
I hoped a version compiled using the new Sailfish OS SDK 1701 would fix it, but that was not the case.

**Comment by djselbeck** [comment]
At the moment I'm not able to reproduce this. Can you build a version with debugging and get a stacktrace perhaps?

I've tested the binary from the Jolla Store on a Jolla Phone and Jolla Tablet for 24h now.

**Comment by djselbeck** [comment]
Now it crashed ;), I'll investigate it

**Comment by a-dekker** [comment]
For what it's worth: your daedalus player suffers from the exact same thing, so it should be shared code. And another symptom I noticed is that the underlining of the playing song is missing most of the time (could be related).

**Comment by djselbeck** [comment]
If you don't mind, can you try 908c056ffa833e540fa9836ef3353056629eaf02 please 😸 . It looks like it fixes the issue?

**Comment by a-dekker** [comment]
This looks very promising! No segfaults so far (used to get them rather soon).
Side question: am I still missing the indication of the current song playing? I is still present in my playlist with internet radio stream, but not when I play an mp3 album.

**Comment by djselbeck** [comment]
The segfaults always came when entering the album tracks view. The current song playing in the playlist is lightly highlighted with an glass effect  like here:

[Image](https://openrepos.net/sites/default/files/packages/965/screenshot-jolla-smpc-tablet.png)

**Comment by a-dekker** [comment]
I am talking about the glass effect, it is missing now. Maybe it is some issue on my phone, I will compile it for the tablet and see if the glass effect is there.

**Comment by djselbeck** [comment]
I have it on both my devices :) (Tablet and original Phone).

**Comment by a-dekker** [comment]
Yep, it looks fine on the tablet build. Must be something on my phone then.
Thanks for another swift response, I can enjoy my music using smpc once again!
