### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by smortex** [djselbeck/smpc#9]
Hello,

Some friends of mine are expecting the french translation of SMPC I contributed some times ago (without having to compile the code themselves).  Have you planned to release a new version of SMPC soon?

Thanks!

**Comment by djselbeck** [comment]
I'll release when the next Sailfish version is stable because I have to. Otherwise SMPC just crashes ;). Sorry for the delay but sailfish really wasn't a priority for me for the time being.

**Comment by djselbeck** [comment]
Released
